#!/bin/bash

me=`basename "$0"`

if [ $# != 2 ]
then
    echo "usage: $me SMLY2_ADDRESS AMOUNT"
    exit 1
fi

smly2_address="$1"
amount=`echo "$2" | bc`

my_address=`smileycoin-cli getnewaddress`
seller_address="BPZgtUcQaRYUCFGJYoY4c2dd6q9WWyGku2"

data="fa32`echo $smly2_address | xxd -p | tr -d '\n'`"

unspent_txid=`smileycoin-cli sendtoaddress $my_address $amount`

if [ -z $unspent_txid ]
then 
    echo "failed to create UTXO of amount $amount"
    exit 1
fi

unspent_tx=`smileycoin-cli getrawtransaction $unspent_txid 2> /dev/null`
if [ -z $unspent_tx ]
then 
    echo "failed to fetch the raw transaction of the previously created utxo $unspent_txid"
    exit 1
fi

raw=`smileycoin-cli createrawtransaction "[{\"txid\":\"$unspent_txid\",\"vout\":0}]" "{\"$seller_address\":$amount,\"data\":\"$data\"}"`
signed=`smileycoin-cli signrawtransaction "$raw" | head -2 | tail -1 | sed -e 's/    "hex" : //' -e 's/"//g' -e 's/,//'`

sent_txid=`smileycoin-cli sendrawtransaction "$signed"`
if [ -z $sent_txid ]
then 
    echo "failed to send transaction"
    exit 1
fi

echo "sent $amount to the address of the seller $seller_address with data $data"
echo "$sent_txid"

